CREATE TABLE courses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    short_description TEXT,
    thumbnail_url VARCHAR(255),
    teaser_video_url VARCHAR(255),
    status VARCHAR(255) NOT NULL DEFAULT 'DRAFT',
    created_by VARCHAR(255),
    instructor_id VARCHAR(255),
    category VARCHAR(255),
    level VARCHAR(255),
    duration_time INTEGER,
    deadline INTEGER,
    access_duration_days INTEGER,
    price DOUBLE PRECISION,
    learning_objectives JSON,
    require_sequential_progress BOOLEAN NOT NULL DEFAULT TRUE,
    enforce_deadline_block BOOLEAN NOT NULL DEFAULT FALSE,
    major_version INTEGER NOT NULL DEFAULT 0,
    minor_version INTEGER NOT NULL DEFAULT 0,
    lessons_count INTEGER NOT NULL DEFAULT 0,
    materials_count INTEGER NOT NULL DEFAULT 0,
    students_count INTEGER NOT NULL DEFAULT 0,
    reviews_count INTEGER NOT NULL DEFAULT 0,
    rating_average DOUBLE PRECISION,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_courses_created_by FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT fk_courses_instructor FOREIGN KEY (instructor_id) REFERENCES admins (user_id),
    CONSTRAINT ck_courses_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED'))
);

CREATE INDEX idx_courses_status ON courses (status);
CREATE INDEX idx_courses_instructor ON courses (instructor_id);

CREATE TABLE course_prerequisites (
    course_id INTEGER NOT NULL,
    prerequisite_course_id INTEGER NOT NULL,
    PRIMARY KEY (course_id, prerequisite_course_id),
    CONSTRAINT fk_course_prereq_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE,
    CONSTRAINT fk_course_prereq_target FOREIGN KEY (prerequisite_course_id) REFERENCES courses (id) ON DELETE CASCADE,
    CONSTRAINT ck_course_prereq_not_self CHECK (course_id <> prerequisite_course_id)
);

CREATE TABLE course_materials (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id INTEGER NOT NULL,
    title VARCHAR(255) NOT NULL,
    file_url VARCHAR(255) NOT NULL,
    file_type VARCHAR(255),
    file_size_bytes BIGINT,
    "order" INTEGER,
    created_at TIMESTAMP,
    CONSTRAINT fk_course_materials_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE
);

CREATE INDEX idx_course_materials_course ON course_materials (course_id);

CREATE TABLE course_change_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id INTEGER NOT NULL,
    changed_by VARCHAR(255),
    description TEXT NOT NULL,
    major_version INTEGER NOT NULL DEFAULT 0,
    minor_version INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP,
    CONSTRAINT fk_course_change_log_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE,
    CONSTRAINT fk_course_change_log_user FOREIGN KEY (changed_by) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX idx_course_change_log_course ON course_change_log (course_id);

CREATE TABLE modules (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id INTEGER NOT NULL,
    title VARCHAR(255) NOT NULL,
    "order" INTEGER NOT NULL,
    CONSTRAINT fk_modules_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE,
    CONSTRAINT uk_modules_course_order UNIQUE (course_id, "order")
);

CREATE TABLE module_prerequisites (
    module_id INTEGER NOT NULL,
    prerequisite_module_id INTEGER NOT NULL,
    PRIMARY KEY (module_id, prerequisite_module_id),
    CONSTRAINT fk_module_prereq_module FOREIGN KEY (module_id) REFERENCES modules (id) ON DELETE CASCADE,
    CONSTRAINT fk_module_prereq_target FOREIGN KEY (prerequisite_module_id) REFERENCES modules (id) ON DELETE CASCADE,
    CONSTRAINT ck_module_prereq_not_self CHECK (module_id <> prerequisite_module_id)
);

CREATE TABLE content (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_id INTEGER NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    type VARCHAR(255) NOT NULL,
    url VARCHAR(255),
    duration_minutes INTEGER,
    is_free BOOLEAN NOT NULL DEFAULT FALSE,
    "order" INTEGER NOT NULL,
    recursos JSON,
    created_at TIMESTAMP,
    CONSTRAINT fk_content_module FOREIGN KEY (module_id) REFERENCES modules (id) ON DELETE CASCADE,
    CONSTRAINT ck_content_type CHECK (type IN ('VIDEO', 'TEXT', 'FILE'))
);

CREATE INDEX idx_content_module ON content (module_id);
